Major update
vectara/vectara-ingest pull request #8
Opened 2023-06-21 13:42 UTC by ofermend

- New crawler Arxiv: get top research papers by citations
- Including instructions to run on Windows and generally updated and simplified the getting started
- Indexer much improved: shorter time to retrieve pages using Playwright without pulling images to shorten load time, reusing playwright browser to reduce resource load, and more.
- After a lot of testing, using trafilatura to extract HTML content - it performs the best and removes the issue we had with hidden content.
- Various other general improvements and bug fixes.

2023-06-21 13:44 UTC, ofermend commented on README.md
> +For Windows,
Windows is complicated. The best way I found to install on windows is to use WSL and thus these instructions.

2023-06-21 13:44 UTC, ofermend commented on config/vectara-docs.yaml
> +  extensions_to_ignore: ["php", "java", "py", "js"]
Added ability to specify extensions to ignore in docs crawler.

2023-06-21 13:46 UTC, ofermend commented on core/indexer.py
> +        p = sync_playwright().start()
This generates a browser instance that does not need to be recreated every time, reducing time to launch the browser every time, and saves memory resources too.

2023-06-21 13:46 UTC, ofermend commented on core/indexer.py
> +    def fetch_content_with_timeout(self, url: str, timeout: int = 30):
Moved back to sync fetch since it's simpler and has the timeout variable.

2023-06-21 13:47 UTC, ofermend commented on core/indexer.py
> +        page.route("**/*", lambda route: route.abort()  # do not load images as they are unnecessary for our purpose
This results in images being ignored in the page, so that we don't spend time loading them. Results in 2-3x speedup.

2023-06-21 13:48 UTC, ofermend commented on crawlers/arxiv_crawler.py
> +        base_url = "https://api.semanticscholar.org/v1/paper/arXiv:"
Arxiv does not have citations. so using semantic scholar to get that.

2023-06-21 13:48 UTC, ofermend commented on crawlers/discourse_crawler.py
> +        self.session = requests.Session()
Using requests.Session() so a session is not created every time.

2023-06-21 13:49 UTC, ofermend commented on crawlers/fmp_crawler.py
> +                    url = rel_filings[0]['finalLink'] if len(rel_filings)>0 else None
bugfix: finalLink is the correct URL of the 10-K

2023-06-21 13:50 UTC, ofermend commented on crawlers/fmp_crawler.py
> -            # income statements
I didnt find these income_statement and cashflow_statement "Artificial" documents to help with anything, and they don't have a URL to point to as reference, so removing for now.

2023-06-21 13:52 UTC, ofermend commented on crawlers/website_crawler.py
> +            url_regex = [re.compile(r) for r in self.cfg.website_crawler.url_regex]
url_regex is now a list allowing multiple patterns

2023-06-22 13:44 UTC, cjcenizal approved these changes
I didn't test this stuff locally and I'm not very familiar with the codebase, so my review is fairly superficial. But from what I could understand these look like good improvements. Had a few minor suggestions.

2023-06-22 13:44 UTC, cjcenizal commented on README.md
> +For Microsoft Windows, make sure you run this command from within the WSL environment (after running `wsl` to enter the linux environment).
Nit: "Linux" should be capitalized

2023-06-22 13:44 UTC, cjcenizal commented on config/legalaid-IL.yaml
> +  corpus_id: 166
Nit: I suggest lower-casing the name "legalaid-il" for consistency. Perhaps even writing it out would make it more readable: "legalaid-illinois"

2023-06-22 13:44 UTC, cjcenizal commented on core/indexer.py
> +        p = sync_playwright().start()
Would it be helpful to folks if this was a comment in the code?

2023-06-22 13:44 UTC, cjcenizal commented on crawlers/arxiv_crawler.py
> +        base_url = "https://api.semanticscholar.org/v1/paper/arXiv:"
I think this would be a great code comment, because of the context it provides.

2023-06-25 20:34 UTC, eskibars requested changes

2023-06-25 20:34 UTC, eskibars commented on crawlers/CRAWLERS.md
> +  <tr>
Can you please just double check that all of these icons are licensed for public use

2023-06-25 20:34 UTC, eskibars commented on crawlers/arxiv_crawler.py
> +        if self.cfg.arxiv_crawler.sort_by == 'citations':
Should we throw an exception if, after filtering, papers is an empty array?

2023-06-25 20:34 UTC, eskibars commented on core/indexer.py
> +from trafilatura import extract, extract_metadata
trafilatura is licensed under GPL 3, and is thus not legally compatible with the Apache 2 license.  We must drop it

2023-06-25 20:34 UTC, eskibars commented on crawlers/docusaurus_crawler.py
> +        self.extensions_to_ignore = list(set(self.cfg.docusaurus_crawler.extensions_to_ignore + ["png", "svg", "jpeg", "jpg", "gif", "mp4"]))
Can you sort these alphabetically?  Eventually, we should make these configurable

2023-06-25 20:34 UTC, eskibars commented on crawlers/pmc_crawler.py
>  from lxml import etree
I just noticed this.  We should fix this quickly by replacing this with a better XML parser: lxml/etree has serious security issues

2023-06-25 20:34 UTC, eskibars commented on requirements.txt
> +psycopg2-binary==2.9.6
psycopg2-binary is LGPL licensed and we should remove it from the dependencies

2023-06-25 22:20 UTC, ofermend commented on config/legalaid-IL.yaml
> +  corpus_id: 166
Since no API keys are provided, it's not a real security risk. Am I wrong?
If we remove this it becomes difficult to include examples. I really use these all the time (e.g. for regression) and in this case would need to copy them in/out all the time.

2023-06-25 22:21 UTC, ofermend commented on config/vectara-jira.yaml
> +  jira_base_url: "https://vectara.atlassian.net/"
Again, similar to corpus ID, if I do this, then I can't use it internally.
This is doable in general, since we now use the docker-hub and I can probably create that outside. But if working on an internal PR (docker-hub not yet updated) it becomes super annoying and error prone to test.

2023-06-25 22:26 UTC, ofermend commented on crawlers/pmc_crawler.py
>  from lxml import etree
compliments I think of GPT4. Can you pls share what the issues are and what is recommneded to use instead?

2023-06-26 21:51 UTC, merged